server:
  port: 8083
spring:
  application:
    name: sms-service
ly:
  sms:
    accessKeyId: LTAI4Fs2zXDAndV4BrL13isS #你自己的accessKeyId
    accessKeySecret: 13uMLfRdDGINxgdy0ywqtCTtpc9PnS #你自己的accessKeySecret
    signName: 乐优商城  #签名名称
    verifyCodeTemplateCode: SMS_182541633 #模板名称
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    tradeType: NATIVE
    spbillCreateIp: 127.0.0.1
    notifyUrl: http://myhxms.natappfree.cc/wxpay/notify